### ISSUE TITLE
Add support for `azureblob`

### ISSUE THREAD

**Issue by tvandelooij** [MeltanoLabs/target-jsonl-blob#105]
## Context

The `README` describes that support for Azure Blob is available using `azblob`. However, when running it didn't work and it resulted in the following error message:

```bash
Unable to open bucket, open blob.Bucket: no driver registered for "azblob" for URL "azblob://<container-name>"; available schemes: file, gs, s3
```

I [forked](https://github.com/tvandelooij/target-jsonl-blob/tree/add-support-for-azblob) the project to include `"gocloud.dev/blob/azureblob"` and it is working for me. 

However, my experience with Go is limited so I am not sure if I did it correctly regarding Go versions and the `go.mod` file.

**Comment by edgarrmondragon** [comment]
The change over on your fork look good to me 🙂. A PR would be welcome!

**Comment by tvandelooij** [comment]
> The change over on your fork look good to me 🙂. A PR would be welcome!

Thanks! Created a PR #106

**Comment by edgarrmondragon** [comment]
Closed by #106

**Comment by edgarrmondragon** [comment]
Thanks @tvandelooij!

**Comment by tvandelooij** [comment]
> Thanks @tvandelooij!

You're welcome! 😄
